### ISSUE TITLE
Template option is not read when initializing

### ISSUE THREAD

**Issue by Zhong-z** [DannyBen/icodi#14]
<img width="1908" alt="Screenshot 2023-03-05 at 21 57 44" src="https://user-images.githubusercontent.com/5219229/222956384-9192a485-a08a-4091-a2c7-4d0673d34734.png">

Though workaround is available, by passing `html` during `render`

**Comment by DannyBen** [comment]
Fixed and released in 0.1.4 - thanks for the report and the PR.

**Comment by Zhong-z** [comment]
Awesome! Thanks for being so responsive! Glad it helped.
